=== 4li77l3n00b/vocabular_wallpaper/Level_6_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Level_6_2" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Level_6_2">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="4oJV+NwrhUeCVQCBcmrHrg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADiglX43CuFR4JVAIFyaseuAAAAAEi9CTqW7eVAAAAAAAAAAABMAGUA
dgBlAGwAXwA2AF8AMgAAAAAAAAD9J9aXFm+NRZ8a23IR5jE3BwAAAOKCVfjcK4VH
glUAgXJqx65zAHAAZQBsAGwAaQBuAGcAAAAAAAAAwCpFFeoQwk2xRx0B077rpwcA
AADiglX43CuFR4JVAIFyaseucABoAG8AbgBlAHQAaQBjAAAAAAAAAP2NX+m2eC9P
hIjUvtwgp5MHAAAA4oJV+NwrhUeCVQCBcmrHrmQAZQBmAGkAbgBpAHQAaQBvAG4A
XwAxAAAAAAAAANKCBSFq9TdHkeetmg6LBZgHAAAA4oJV+NwrhUeCVQCBcmrHrmQA
ZQBmAGkAbgBpAHQAaQBvAG4AXwAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAA
BQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="OrderBy" type="12" value="[Level_6_2].[spelling]"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="spelling" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="/SfWlxZvjUWfGttyEeYxNw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4932"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="phonetic" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="wCpFFeoQwk2xRx0B077rpw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4824"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="definition_1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="/Y1f6bZ4L0+EiNS+3CCnkw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3276"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="definition_2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="0oIFIWr1N0eR562aDosFmA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4356"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== 4li77l3n00b/vocabular_wallpaper/Level_6_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Level_6_2.xsd" generated="2022-12-13T16:41:23">
<Level_6_2>
<spelling>abnormal</spelling>
<phonetic>[æb′nɔ:mә]</phonetic>
<definition_1>a.不正常的；变态的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>abolish</spelling>
<phonetic>[ә′bɔliʃ]</phonetic>
<definition_1>vt.废除，取消</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>abundance</spelling>
<phonetic>[ә′bΛndәns]</phonetic>
<definition_1>n.丰富，充裕</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>accessory</spelling>
<phonetic>[æk′sesәri]</phonetic>
<definition_1>n.同谋</definition_1>
<definition_2>a.附属的</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>accommodate</spelling>
<phonetic>[ә′kɔmәdeit]</phonetic>
<definition_1>vt.容纳；供应，供给</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>accord</spelling>
<phonetic>[ә′kɔ:d]</phonetic>
<definition_1>vt.一致(~with)；给予</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>acknowledge</spelling>
<phonetic>[әk′nɔlidʒ]</phonetic>
<definition_1>vt.承认；告知收到</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>acquaint</spelling>
<phonetic>[ә′kweint]</phonetic>
<definition_1>vt.使认识，使了解</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>acquisition</spelling>
<phonetic>[`ækwi′ziʃәn]</phonetic>
<definition_1>n.获得,添加的物品</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>activate</spelling>
<phonetic>[`æktiveit]</phonetic>
<definition_1>vt.刺激,使活动</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>acute</spelling>
<phonetic>[ә′kju:t]</phonetic>
<definition_1>a.敏锐的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>administer</spelling>
<phonetic>[әd′ministә]</phonetic>
<definition_1>vt.执行,管理,治理,</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>adverse</spelling>
<phonetic>[`ædvә:s]</phonetic>
<definition_1>a.不利的,敌对的,相反的,逆的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>advertise</spelling>
<phonetic>[`ædvәtaiz]</phonetic>
<definition_1>vt.通知</definition_1>
<definition_2>vi.登广告</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>advocate</spelling>
<phonetic>[`ædvәkit]</phonetic>
<definition_1>n.辩护者</definition_1>
<definition_2>vt.拥护</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>affiliate</spelling>
<phonetic>[ә′filieit]</phonetic>
<definition_1>vt.附属,接纳</definition_1>
<definition_2>vi.有关</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>affirm</spelling>
<phonetic>[ә′fә:m]</phonetic>
<definition_1>vt.断言，批准；证实</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>aggravate</spelling>
<phonetic>[`ægrәveit]</phonetic>
<definition_1>vt.使恶化,使更加重</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>agreeable</spelling>
<phonetic>[ә′griәbl]</phonetic>
<definition_1>a.惬意的；同意的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>alert</spelling>
<phonetic>[ә′lә:t]</phonetic>
<definition_1>a.警惕的；活跃的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>alliance</spelling>
<phonetic>[ә′laiәns]</phonetic>
<definition_1>n.联盟,联合</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>allocate</spelling>
<phonetic>[`ælәkeit]</phonetic>
<definition_1>vt.分派,分配</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>allowance</spelling>
<phonetic>[ә′lauәns]</phonetic>
<definition_1>n津贴，补助费</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>alongside</spelling>
<phonetic>[ә′lɔŋ′said]</phonetic>
<definition_1>prep.在…旁边</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>alternate</spelling>
<phonetic>[ɔ:l′tә:nit]</phonetic>
<definition_1>vt.使交替</definition_1>
<definition_2>a.交替的</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>ambiguous</spelling>
<phonetic>[æm′bigjuәs]</phonetic>
<definition_1>a.模棱两可的；分歧的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>ambitious</spelling>
<phonetic>[æm′biʃәs]</phonetic>
<definition_1>a.有雄心的；热望的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>ample</spelling>
<phonetic>[`æmpl]</phonetic>
<definition_1>a.足够的；宽敞的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>amplify</spelling>
<phonetic>[`æmplifai]</phonetic>
<definition_1>vt.放大，增强；扩大</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>analogy</spelling>
<phonetic>[ә′nælәdʒi]</phonetic>
<definition_1>n.相似，类似；比拟</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>analytic</spelling>
<phonetic>[ænә′litik]</phonetic>
<definition_1>a.分析的,解析的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>analytical</spelling>
<phonetic>[ænә′litikl]</phonetic>
<definition_1>a.分析的,解析的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>angel</spelling>
<phonetic>[`eindʒәl]</phonetic>
<definition_1>n.天使，神差，安琪儿</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>anniversary</spelling>
<phonetic>[,æni′vә:sәri]</phonetic>
<definition_1>n.周年纪念日</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>anonymous</spelling>
<phonetic>[ә′nɔnimәs]</phonetic>
<definition_1>a.匿名的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>antarctic</spelling>
<phonetic>[ænt′a:ktik]</phonetic>
<definition_1>a.南极的</definition_1>
<definition_2>n.南极区</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>antique</spelling>
<phonetic>[æn′ti:k]</phonetic>
<definition_1>a.古代的</definition_1>
<definition_2>n.古物</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>appreciable</spelling>
<phonetic>[ә′pri:ʃәbl]</phonetic>
<definition_1>a.可估价的；可察觉的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>apprehension</spelling>
<phonetic>[æpri′henʃәn]</phonetic>
<definition_1>n.理解,忧惧,逮捕</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>architect</spelling>
<phonetic>[`a:kitekt]</phonetic>
<definition_1>n.建筑师；创造者</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>arctic</spelling>
<phonetic>[`a:ktik]</phonetic>
<definition_1>a.北极的</definition_1>
<definition_2>n.北极</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>array</spelling>
<phonetic>[ә′rei]</phonetic>
<definition_1>vt.装扮</definition_1>
<definition_2>n.队列；排列</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>articulate</spelling>
<phonetic>[a:′tikjulit]</phonetic>
<definition_1>a.发音清晰的，听得懂的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>assimilate</spelling>
<phonetic>[ә′simileit]</phonetic>
<definition_1>vt.使同化,吸收,比较</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>assumption</spelling>
<phonetic>[ә′sΛmpʃәn]</phonetic>
<definition_1>n.采取；假定；傲慢</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>assurance</spelling>
<phonetic>[ә′ʃuәrәns]</phonetic>
<definition_1>n.保证；财产转让书</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>astronomy</spelling>
<phonetic>[әs′trɔnәmi]</phonetic>
<definition_1>n.天文学</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>attendance</spelling>
<phonetic>[ә′tendәns]</phonetic>
<definition_1>n.到场；出席人数</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>attendant</spelling>
<phonetic>[ә′tendәnt]</phonetic>
<definition_1>n.侍者；护理人员</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>augment</spelling>
<phonetic>[ɔ:g′ment,`ɔ:gmәnt]</phonetic>
<definition_1>vt.vi.n.增加,增大</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>authoritative</spelling>
<phonetic>[ɔ:′θɔritәtiv]</phonetic>
<definition_1>a.权威的,有权威的,命令式的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>authorize</spelling>
<phonetic>[`ɔ:θәraiz]</phonetic>
<definition_1>vt.授权与,批准,委托代替</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>automation</spelling>
<phonetic>[ɔ:tә′meiʃәn]</phonetic>
<definition_1>n.自动，自动化</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>avail</spelling>
<phonetic>[ә′veil]</phonetic>
<definition_1>vt.有益于</definition_1>
<definition_2>n.效用</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>bachelor</spelling>
<phonetic>[`bætʃәlә]</phonetic>
<definition_1>n.未婚男子；学士</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>baffle</spelling>
<phonetic>[`bæfl]</phonetic>
<definition_1>vt.使挫折</definition_1>
<definition_2>n.迷惑</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>bald</spelling>
<phonetic>[bɔ:ld]</phonetic>
<definition_1>a.秃头的；无毛的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>ballet</spelling>
<phonetic>[`bælei,]</phonetic>
<definition_1>n.芭蕾舞；舞剧</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>ban</spelling>
<phonetic>[bæn]</phonetic>
<definition_1>n.禁令</definition_1>
<definition_2>vt.禁止,取缔</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>bankrupt</spelling>
<phonetic>[`bæŋkrәpt]</phonetic>
<definition_1>a.破产的</definition_1>
<definition_2>vt.使破产</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>barely</spelling>
<phonetic>[`bɛәli]</phonetic>
<definition_1>ad.仅仅，勉强</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>barren</spelling>
<phonetic>[`bærәn]</phonetic>
<definition_1>a.贫瘠的；不妊的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>basement</spelling>
<phonetic>[`beismәnt]</phonetic>
<definition_1>n.地下室；地窖；底层</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>bearing</spelling>
<phonetic>[`bɛәriŋ]</phonetic>
<definition_1>n.支承；忍受；方位</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>beforehand</spelling>
<phonetic>[bi′fɔ:hænd]</phonetic>
<definition_1>ad.预先；提前地</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>betray</spelling>
<phonetic>[bi′trei]</phonetic>
<definition_1>vt.背叛；辜负；泄漏</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>bewilder</spelling>
<phonetic>[bi′wildә]</phonetic>
<definition_1>vt.迷惑，把…弄糊涂</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>biography</spelling>
<phonetic>[bai′ɔgrәfi]</phonetic>
<definition_1>n.传记</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>blaze</spelling>
<phonetic>[bleiz]</phonetic>
<definition_1>n.火；闪光</definition_1>
<definition_2>vi.燃烧</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>bleak</spelling>
<phonetic>[bli:k]</phonetic>
<definition_1>a.萧瑟的,苍白的,荒凉的</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>bless</spelling>
<phonetic>[bles]</phonetic>
<definition_1>vt.为…祝福</definition_1>
</Level_6_2>
<Level_6_2>
<spelling>blossom</spelling>
<phonetic>[`blɔsәm]</phonetic>
<definition_1>n.花，开花</definition_1>
<definition_2>vi.开花</definition_2>
</Level_6_2>
<Level_6_2>
<spelling>boom</spelling>
<phonetic>[bu:m]</phonetic>
<definition_1>vi.n.急速发展,繁荣,隆隆响</definition_1>
</Level_6_2>
<Level_6_2>
