=== 4li77l3n00b/vocabular_wallpaper/Level_6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Level_6" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Level_6">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="HyRKxJpOp0qdEiKNB8bvmg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAfJErEmk6nSp0SIo0Hxu+aAAAAAPWxlbqT7eVAAAAAAAAAAABMAGUA
dgBlAGwAXwA2AAAAAAAAABR4C0XEgStLvtu02XS4/tYHAAAAHyRKxJpOp0qdEiKN
B8bvmmkAZAAAAAAAAACavS7U8rpyQIoylQHsY8FbBwAAAB8kSsSaTqdKnRIijQfG
75pzAHAAZQBsAGwAaQBuAGcAAAAAAAAA4vBp4QxA30agOrZmJWep3AcAAAAfJErE
mk6nSp0SIo0Hxu+acABoAG8AbgBlAHQAaQBjAAAAAAAAAJa6VQB4RjRGiEkBr/rA
+PYHAAAAHyRKxJpOp0qdEiKNB8bvmmQAZQBmAGkAbgBpAHQAaQBvAG4AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="id" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="FHgLRcSBK0u+27TZdLj+1g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="spelling" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="mr0u1PK6ckCKMpUB7GPBWw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="phonetic" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4vBp4QxA30agOrZmJWep3A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="definition" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="lrpVAHhGNEaISQGv+sD49g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="9156"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== 4li77l3n00b/vocabular_wallpaper/Level_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Level_6.xsd" generated="2022-12-13T14:50:02">
<Level_6>
<id>1</id>
<spelling>consistent</spelling>
<phonetic>[kənˈsɪstənt]</phonetic>
<definition>adj.始终如一的，一贯的</definition>
</Level_6>
<Level_6>
<id>2</id>
<spelling>battery</spelling>
<phonetic>[ˈbætəri]</phonetic>
<definition>n.电池，蓄电池adj.笼养的，层架式养殖的</definition>
</Level_6>
<Level_6>
<id>3</id>
<spelling>competent</spelling>
<phonetic>[ˈkɑːmpɪtənt]</phonetic>
<definition>adj.能干的，能胜任的</definition>
</Level_6>
<Level_6>
<id>4</id>
<spelling>preserve</spelling>
<phonetic>[prɪˈzɜːrv]</phonetic>
<definition>v.保护，维护n.果酱，腌菜</definition>
</Level_6>
<Level_6>
<id>5</id>
<spelling>possession</spelling>
<phonetic>[pəˈzeʃn]</phonetic>
<definition>n.拥有，持有</definition>
</Level_6>
<Level_6>
<id>6</id>
<spelling>wildfire</spelling>
<phonetic>[ˈwaɪldfaɪər]</phonetic>
<definition>n.野火，烈火</definition>
</Level_6>
<Level_6>
<id>7</id>
<spelling>compact</spelling>
<phonetic>[kəmˈpækt；ˈkɑːmpækt]</phonetic>
<definition>adj.小型的，袖珍的n.带镜小粉盒v.压紧，压实</definition>
</Level_6>
<Level_6>
<id>8</id>
<spelling>defy</spelling>
<phonetic>[dɪˈfaɪ]</phonetic>
<definition>v.违抗，不服从</definition>
</Level_6>
<Level_6>
<id>9</id>
<spelling>absolutely</spelling>
<phonetic>[ˈæbsəluːtli]</phonetic>
<definition>adv.绝对地，完全地</definition>
</Level_6>
<Level_6>
<id>10</id>
<spelling>filter</spelling>
<phonetic>[ˈfɪltər]</phonetic>
<definition>n.过滤器v.过滤【名】（Filter）（德）菲尔特（人名）</definition>
</Level_6>
<Level_6>
<id>11</id>
<spelling>server</spelling>
<phonetic>[ˈsɜːrvər]</phonetic>
<definition>n.服务器【名】（Server）（美、俄、西、法）塞尔韦尔（人名）</definition>
</Level_6>
<Level_6>
<id>12</id>
<spelling>spoil</spelling>
<phonetic>[spɔɪl]</phonetic>
<definition>v.破坏，糟蹋n.赃物，战利品（the spoils）</definition>
</Level_6>
<Level_6>
<id>13</id>
<spelling>rustle</spelling>
<phonetic>[ˈrʌsl]</phonetic>
<definition>v.（使）沙沙作响n.沙沙声</definition>
</Level_6>
<Level_6>
<id>14</id>
<spelling>diversion</spelling>
<phonetic>[daɪˈvɜːrʒn]</phonetic>
<definition>n.转向，转移</definition>
</Level_6>
<Level_6>
<id>15</id>
<spelling>complaint</spelling>
<phonetic>[kəmˈpleɪnt]</phonetic>
<definition>n.抱怨，投诉</definition>
</Level_6>
<Level_6>
<id>16</id>
<spelling>merge</spelling>
<phonetic>[mɜːrdʒ]</phonetic>
<definition>v.（使）合并，（使）融合【名】（Merge）（意）梅尔杰（人名）</definition>
</Level_6>
<Level_6>
<id>17</id>
<spelling>priceless</spelling>
<phonetic>[ˈpraɪsləs]</phonetic>
<definition>adj.无价的</definition>
</Level_6>
<Level_6>
<id>18</id>
<spelling>honorary</spelling>
<phonetic>[ˈɑːnəreri]</phonetic>
<definition>adj.荣誉的</definition>
</Level_6>
<Level_6>
<id>19</id>
<spelling>chronic</spelling>
<phonetic>[ˈkrɑːnɪk]</phonetic>
<definition>adj.（疾病）慢性的，长期的【名】（Chronic）（英）克罗尼克（人名）</definition>
</Level_6>
<Level_6>
<id>20</id>
<spelling>extracurricular</spelling>
<phonetic>[ˌekstrəkəˈrɪkjələr]</phonetic>
<definition>adj.课外的</definition>
</Level_6>
<Level_6>
<id>21</id>
<spelling>lobby</spelling>
<phonetic>[ˈlɑːbi]</phonetic>
<definition>v.游说（政治家或政府）n.游说团体，活动集团</definition>
</Level_6>
<Level_6>
<id>22</id>
<spelling>inexhaustible</spelling>
<phonetic>[ˌɪnɪɡˈzɔːstəbl]</phonetic>
<definition>adj.用不完的</definition>
</Level_6>
<Level_6>
<id>23</id>
<spelling>inevitable</spelling>
<phonetic>[ɪnˈevɪtəbl]</phonetic>
<definition>adj.必然发生的，不可避免的n.必然发生的事，不可避免的事</definition>
</Level_6>
<Level_6>
<id>24</id>
<spelling>contamination</spelling>
<phonetic>[kənˌtæmɪˈneɪʃn]</phonetic>
<definition>n.污染</definition>
</Level_6>
<Level_6>
<id>25</id>
<spelling>suspend</spelling>
<phonetic>[səˈspend]</phonetic>
<definition>v.暂停，中止</definition>
</Level_6>
<Level_6>
<id>26</id>
<spelling>imminent</spelling>
<phonetic>[ˈɪmɪnənt]</phonetic>
<definition>adj.即将发生的，临近的</definition>
</Level_6>
<Level_6>
<id>27</id>
<spelling>obesity</spelling>
<phonetic>[oʊˈbiːsəti]</phonetic>
<definition>n.过度肥胖，肥胖症</definition>
</Level_6>
<Level_6>
<id>28</id>
<spelling>aid</spelling>
<phonetic>[eɪd]</phonetic>
<definition>n.帮助v.帮助，援助【名】（Aid）（英、阿拉伯、印）艾德（人名）</definition>
</Level_6>
<Level_6>
<id>29</id>
<spelling>solution</spelling>
<phonetic>[səˈluːʃn]</phonetic>
<definition>n.（问题、困难等的）解决办法</definition>
</Level_6>
<Level_6>
<id>30</id>
<spelling>tuition</spelling>
<phonetic>[tuˈɪʃn]</phonetic>
<definition>n.（尤指对个人或小组的）教学，指导</definition>
</Level_6>
<Level_6>
<id>31</id>
<spelling>esteem</spelling>
<phonetic>[ɪˈstiːm]</phonetic>
<definition>n.尊重，敬重v.尊重，敬重</definition>
</Level_6>
<Level_6>
<id>32</id>
<spelling>purchase</spelling>
<phonetic>[ˈpɜːrtʃəs]</phonetic>
<definition>n.购买，采购v.购买，采购</definition>
</Level_6>
<Level_6>
<id>33</id>
<spelling>incorporate</spelling>
<phonetic>[ɪnˈkɔːrpəreɪt]</phonetic>
<definition>v.包含，合并adj.合成一体的，合并的</definition>
</Level_6>
<Level_6>
<id>34</id>
<spelling>prevail</spelling>
<phonetic>[prɪˈveɪl]</phonetic>
<definition>v.流行，盛行</definition>
</Level_6>
<Level_6>
<id>35</id>
<spelling>irrational</spelling>
<phonetic>[ɪˈræʃənl]</phonetic>
<definition>adj.非理性的，不合逻辑的，荒谬的n.无理数</definition>
</Level_6>
<Level_6>
<id>36</id>
<spelling>inherent</spelling>
<phonetic>[ɪnˈherəntˌɪnˈhɪrənt]</phonetic>
<definition>adj.内在的，固有的</definition>
</Level_6>
<Level_6>
<id>37</id>
<spelling>overexcited</spelling>
<phonetic>[ˌoʊvərɪkˈsaɪtɪd]</phonetic>
<definition>adj.过励磁的v.使过分激动或兴奋（overexcite 的过去式）</definition>
</Level_6>
<Level_6>
<id>38</id>
<spelling>preference</spelling>
<phonetic>[ˈprefrəns]</phonetic>
<definition>n.偏爱，偏好</definition>
</Level_6>
<Level_6>
<id>39</id>
<spelling>evolution</spelling>
<phonetic>[ˌevəˈluːʃn]</phonetic>
<definition>n.进化（论）</definition>
</Level_6>
<Level_6>
<id>40</id>
<spelling>exotic</spelling>
<phonetic>[ɪɡˈzɑːtɪk]</phonetic>
<definition>adj.奇异的，异国风情的n.外来植物，外来动物</definition>
</Level_6>
<Level_6>
<id>41</id>
<spelling>stockbroker</spelling>
<phonetic>[ˈstɑːkbroʊkər]</phonetic>
<definition>n.[金融]股票经纪人n.（Stockbroker）人名</definition>
</Level_6>
<Level_6>
<id>42</id>
<spelling>misinterpret</spelling>
<phonetic>[ˌmɪsɪnˈtɜːrprət]</phonetic>
<definition>v.曲解，误解</definition>
</Level_6>
<Level_6>
<id>43</id>
<spelling>prosperity</spelling>
<phonetic>[prɑːˈsperəti]</phonetic>
<definition>n.繁荣，成功</definition>
</Level_6>
<Level_6>
<id>44</id>
<spelling>Tank</spelling>
<phonetic>[tæŋk]</phonetic>
<definition>n.（储存液体或气体的）箱，罐，缸v.彻底失败，破产【名】（Tank）（德、土、阿塞、土库、挪）汤克（人名）</definition>
</Level_6>
<Level_6>
<id>45</id>
<spelling>outdated</spelling>
<phonetic>[ˌaʊtˈdeɪtɪd]</phonetic>
<definition>adj.过时的，陈旧的v.使过时（outdate 的过去式和过去分词形式）</definition>
</Level_6>
<Level_6>
<id>46</id>
<spelling>outnumber</spelling>
<phonetic>[ˌaʊtˈnʌmbər]</phonetic>
<definition>vt.数目超过</definition>
</Level_6>
<Level_6>
<id>47</id>
<spelling>supervisor</spelling>
<phonetic>[ˈsuːpərvaɪzər]</phonetic>
<definition>n.监督者，管理者</definition>
</Level_6>
<Level_6>
<id>48</id>
<spelling>fluctuate</spelling>
<phonetic>[ˈflʌktʃueɪt]</phonetic>
<definition>v.波动，起伏不定</definition>
</Level_6>
<Level_6>
<id>49</id>
<spelling>substance</spelling>
<phonetic>[ˈsʌbstəns]</phonetic>
<definition>n.物质，材料</definition>
</Level_6>
<Level_6>
<id>50</id>
<spelling>profitable</spelling>
<phonetic>[ˈprɑːfɪtəbl]</phonetic>
<definition>adj.盈利的，有利可图的</definition>
</Level_6>
<Level_6>
<id>51</id>
<spelling>markedly</spelling>
<phonetic>[ˈmɑːrkɪdli]</phonetic>
<definition>adv.显著地，明显地</definition>
</Level_6>
<Level_6>
<id>52</id>
<spelling>ineffective</spelling>
<phonetic>[ˌɪnɪˈfektɪv]</phonetic>
<definition>adj.无效果的，不起作用的</definition>
</Level_6>
<Level_6>
<id>53</id>
<spelling>bleak</spelling>
<phonetic>[bliːk]</phonetic>
<definition>adj.不乐观的，无望的n.欧鲌</definition>
</Level_6>
<Level_6>
<id>54</id>
<spelling>optimistic</spelling>
<phonetic>[ˌɑːptɪˈmɪstɪk]</phonetic>
<definition>adj.乐观的，乐观主义的</definition>
</Level_6>
<Level_6>
<id>55</id>
<spelling>ultimate</spelling>
<phonetic>[ˈʌltɪmət]</phonetic>
<definition>adj.最终的，最后的n.最好的事物，最终的事物v.结束</definition>
</Level_6>
<Level_6>
<id>56</id>
<spelling>consumption</spelling>
<phonetic>[kənˈsʌmpʃn]</phonetic>
<definition>n.消费，消耗</definition>
</Level_6>
<Level_6>
<id>57</id>
<spelling>foster</spelling>
<phonetic>[ˈfɑːstər]</phonetic>
<definition>v.促进，培养adj.代养的，寄养的【名】（Foster）福斯特（人名）</definition>
</Level_6>
<Level_6>
<id>58</id>
<spelling>receipt</spelling>
<phonetic>[rɪˈsiːt]</phonetic>
<definition>n.发票，收据v.在（账单）上注明收讫字样</definition>
</Level_6>
<Level_6>
<id>59</id>
<spelling>harsh</spelling>
<phonetic>[hɑːrʃ]</phonetic>
<definition>adj.（环境）恶劣的，艰苦的【名】（Harsh）哈什（人名）</definition>
</Level_6>
<Level_6>
<id>60</id>
<spelling>misfortune</spelling>
<phonetic>[ˌmɪsˈfɔːrtʃən]</phonetic>
<definition>n.厄运，不幸</definition>
</Level_6>
<Level_6>
<id>61</id>
<spelling>citation</spelling>
<phonetic>[saɪˈteɪʃn]</phonetic>
<definition>n.引文，引语</definition>
</Level_6>
<Level_6>
<id>62</id>
<spelling>rape</spelling>
<phonetic>[reɪp]</phonetic>
<definition>n.强奸罪，强奸案v.强奸，强暴</definition>
</Level_6>
<Level_6>
<id>63</id>
<spelling>ecological</spelling>
<phonetic>[ˌiːkəˈlɑːdʒɪkl]</phonetic>
<definition>adj.生态的，生态学的</definition>
</Level_6>
<Level_6>
<id>64</id>
<spelling>lag</spelling>
<phonetic>[læɡ]</phonetic>
<definition>v.掉队，落后于n.（两件事的）时间间隔adj.最后的【名】（Lag）（俄）拉格（人名）</definition>
</Level_6>
<Level_6>
<id>65</id>
<spelling>controversy</spelling>
<phonetic>[ˈkɑːntrəvɜːrsi]</phonetic>
<definition>n.争论，争议</definition>
</Level_6>
<Level_6>
<id>66</id>
<spelling>cornerstone</spelling>
<phonetic>[ˈkɔːrnərstoʊn]</phonetic>
<definition>n.基石，支柱，基础</definition>
</Level_6>
<Level_6>
<id>67</id>
<spelling>erect</spelling>
<phonetic>[ɪˈrekt]</phonetic>
<definition>v.搭建，建造adj.竖直的，直立的</definition>
</Level_6>
<Level_6>
<id>68</id>
<spelling>prematurely</spelling>
<phonetic>[ˌpriːməˈtʃʊrliˌˌpriːməˈtʊrli]</phonetic>
<definition>adv.过早地</definition>
</Level_6>
<Level_6>
<id>69</id>
<spelling>initiative</spelling>
<phonetic>[ɪˈnɪʃətɪv]</phonetic>
<definition>n.措施，倡议</definition>
</Level_6>
<Level_6>
<id>70</id>
<spelling>dilute</spelling>
<phonetic>[daɪˈluːt]</phonetic>
<definition>v.稀释，冲淡adj.稀释了的，冲淡了的</definition>
</Level_6>
